#!/bin/bash

if ! [ $1 ]; then echo -e "File name is not specified.\\nusage: ap <file>\\n\\nexample: ap a\\tcreate a.cpp"; exit 0; fi
if [ -e $1.cpp ]; then echo "$1.cpp is already exists"; exit 0; fi

cat << EOT >> $1.cpp
# include <algorithm>
# include <cassert>
# include <cctype>
# include <cstdio>
# include <cstdlib>
# include <cstring>
# include <cmath>
# include <iostream>
# include <map>
# include <queue>
# include <set>
# include <sstream>
# include <stack>
# include <string>
# include <vector>
# include <iomanip>

# define rep(i, n) for (int i = 0; i < (int)(n); i++)
# define irep(i, n) for (int i = int(n) - 1; i >= 0; i--)
# define FOR(i, m, n) for (int i = int(m); i < (int)(n); i++)

using namespace std;


int main() {

}
EOT
