#!/bin/bash

if ! [ $1 ]; then echo -e "File name is not specified.\\nusage: ap <file>\\n\\nexample: ap a\\tcreate a.cpp"; exit 0; fi
if [ -e $1.cpp ]; then echo "$1.cpp is already exists"; exit 0; fi

cat << EOT >> $1.cpp
# include <bits/stdc++.h>

# define rep(i, n) for (int i = 0; i < (int)(n); i++)
# define irep(i, n) for (int i = int(n) - 1; i >= 0; i--)
# define FOR(i, m, n) for (int i = int(m); i < (int)(n); i++)

using namespace std;

// namespace utils
namespace utils{
  template <typename T> void print(vector<vector<T>> mat) {
    rep (i, mat.size()) {
      rep (j, mat[0].size()) cout << mat[i][j] << ' ';
      cout << endl;
    }
  }

  template <typename T> void print(vector<T> v) {
    rep (i, v.size()) cout << v[i] << ' ';
    cout << endl;
  }
// end namespace utils
}

int main() {
}
EOT
