#! /bin/sh


if [ -z "$1" ]
then
  echo 'usage: lt <name>'
  exit
fi

mkdir $1 && cd $1

cat << EOT >> Makefile
all:
	platex main.tex
	platex main.tex
	dvipdfmx main
clean:
	rm main.aux
	rm main.dvi
	rm main.log
EOT

cat << EOT >> main.tex
\documentclass[dvipdfmx, twocolumn]{jsarticle}
\usepackage{graphicx}
\usepackage{booktabs}
\\title{}
\\author{himkt}
\date{\\today}

\\begin{document}
\\maketitle
\\section{}
\end{document}
EOT
