# essential
brew 'gcc'

# ruby and python
brew 'python3'

# latest tmux, neovim
brew 'tmux'
brew 'neovim'

# useful tools
brew 'ghq'
brew 'zsh'
brew 'htop'
brew 'tree'
brew 'wget'
brew 'the_silver_searcher'
